name: ghostscript-printer-app
min-version: 2.5
element-path: elements

(@):
  - include/aliases.yml

options:
  arch:
    type: arch
    description: Machine architecture
    variable: arch
    values:
      - aarch64
      - x86_64

sandbox:
  build-arch: "%{arch}"

plugins:
  - origin: junction
    junction: plugins/buildstream-plugins-community.bst
    sources:
      - git_repo
      - patch_queue

sources:
  git_repo:
    config:
      ref-format: git-describe
